services:
  db:
    image: postgres:16-alpine
    container_name: plausible_db
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=plausible
      - POSTGRES_USER=plausible
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U plausible"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - default

  plausible:
    image: ghcr.io/plausible/community-edition:v2
    container_name: plausible_app
    restart: always
    expose:
      - 8000
    depends_on:
      db:
        condition: service_healthy
    environment:
      - BASE_URL=https://${VIRTUAL_HOST}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - DATABASE_URL=postgres://plausible:${POSTGRES_PASSWORD}@db:5432/plausible
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      - VIRTUAL_PORT=8000
    networks:
      - default
      - reverse-proxy

networks:
  reverse-proxy:
    external: true
